# Generated by Django 4.0.6 on 2022-07-29 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('card_no', models.IntegerField()),
                ('exp_date', models.IntegerField()),
                ('cvv_no', models.IntegerField()),
            ],
        ),
    ]
